### ISSUE TITLE
 Add examples where one file has `.js` extension and other file is cjs/mjs?

### ISSUE THREAD

**Issue by trivikr** [sheremet-va/dual-packaging#3]
### Is your feature request related to a problem? Please describe.
The examples are missing where `.js` extension can be present as default in mixed.

<details>
<summary>test-mixed-cjs</summary>

<details>
<summary>index.js</summary>

```js
console.log('cjs module')

module.exports.test = 'test'
```

</details>

<details>
<summary>index.mjs</summary>

```js
console.log('esm module')

export const test = 'test'
```

</details>

<details>
<summary>package.json</summary>

```json
{
    "name": "test-mixed-cjs",
    "exports": {
        ".": {
            "import": "./index.mjs",
            "require": "./index.js"
        }
    }
}
```

</details>

</details>

<details>
<summary>test-mixed-esm</summary>

<details>
<summary>index.cjs</summary>

```js
console.log('cjs module')

module.exports.test = 'test'
```

</details>

<details>
<summary>index.js</summary>

```js
console.log('esm module')

export const test = 'test'
```

</details>

<details>
<summary>package.json</summary>

```json
{
    "name": "test-mixed-esm",
    "exports": {
        ".": {
            "import": "./index.mjs",
            "require": "./index.js"
        }
    },
   "type": "module"
}
```

</details>

</details>

### Describe the solution you'd like
Add `test-mixed-cjs` and `test-mixed-esm` options with test files for each.

### Describe alternatives you've considered
N/A

**Comment by sheremet-va** [comment]
Not sure why? It doesn't really affect anything, not? `mixed` package is about how to do it correctly. I think mentioning that `.cjs` and `.mjs` are ignoring `type` field is enough.

Also, examples already have it, like `tsup` generates js depending on `type`, and the other file is named `cjs/mjs`
