### ISSUE TITLE
Rename test-folder to test-folder-esm and add test-folder-cjs

### ISSUE THREAD

**Issue by trivikr** [sheremet-va/dual-packaging#4]
### Is your feature request related to a problem? Please describe.
The existing example for `test-folder` has example for esm folder. There is not example for cjs folder.

<details>
<summary>test-folder-cjs</summary>

<details>
<summary>cjs/index.js</summary>

```js
console.log('cjs module')

module.exports.test = 'test'
```

</details>

<details>
<summary>cjs/package.json</summary>

```json
{
    "type": "commonjs"
}
```

</details>

<details>
<summary>index.js</summary>

```js
console.log('esm module')

export const test = 'test'
```

</details>

<details>
<summary>package.json</summary>

```json
{
    "name": "test-folder-cjs",
    "exports": {
        ".": {
            "import": "./index.js",
            "require": "./cjs/index.js"
        }
    },
    "type": "module"
}
```

</details>

</details>

### Describe the solution you'd like
Rename `test-folder` to `test-folder-esm` and add `test-folder-cjs`

### Describe alternatives you've considered
Do not add `test-folder-cjs` test case as most folks aren't going to use it.

**Comment by sheremet-va** [comment]
That is the point. You don't need a cjs folder. It's more a matter of preference. I think developers can figure it out 🤔

**Comment by sheremet-va** [comment]
Not sure we should add such examples, I think it would more confusing 🤔
